version: '3'

volumes:
  mongodb_data:

services:
  app:
    build:
      context: ./app
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./app:/app
    command: ["python", "app.py"]
  importer:
    build:
      context: ./importer
      dockerfile: Dockerfile
    volumes:
      - ./importer:/importer
    depends_on:
      - mongodb
    command: ["python", "run.py"]
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data:/data/db