version: '3'

volumes:
  mongodb_data:

services:
  api:
    build:
      context: ./api
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./api:/api
    command: ["python", "api.py"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 127.0.0.1:3000:3000
    command: bash -c "npm install --verbose && npm run dev"
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data:/data/db
# dev infrastructure
  importer:
    build:
      context: ./importer
      dockerfile: Dockerfile
    volumes:
      - ./importer:/importer
    depends_on:
      - mongodb
    command: ["python", "run.py"]